/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.0-alpha.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as posts from "../posts";
import type * as rls from "../rls";
import type * as rowLevelSecurity from "../rowLevelSecurity";
import type * as users from "../users";
import type * as withUser from "../withUser";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  posts: typeof posts;
  rls: typeof rls;
  rowLevelSecurity: typeof rowLevelSecurity;
  users: typeof users;
  withUser: typeof withUser;
}>;
